### ISSUE TITLE
Role position

### ISSUE THREAD

**Issue by j0ri500** [gregzaal/In-Game-Roles#1]
It would be nice if it were possible to change the position of the roles. So it would be also possible that the roles are always in top position.

**Comment by gregzaal** [comment]
Congratulations on finding this obscure, undocumented and mostly unstable bot!

You can move a role to the top by adding it to the whitelist with the `add` command. This will also make it ignore the minimum player threshold (default of 3) and always show people playing that game.

If you have multiple  roles in the whitelist already, use the `movetotop` command.

Not particularly intuitive I know, I plan to rewrite it soon™.
